apiVersion: weave.works/v1alpha1
kind: ProfileInstallation
metadata:
  creationTimestamp: null
  name: pctl-profile
  namespace: default
spec:
  catalog:
    catalog: nginx-catalog
    profile: weaveworks-nginx
    version: v0.1.0
  gitRepository:
    name: flux-system
    namespace: flux-system
  source:
    path: weaveworks-nginx
    tag: weaveworks-nginx/v0.1.0
    url: https://github.com/weaveworks/profiles-examples
status: {}
