apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: pctl-profile-bitnami-nginx-nginx-server
  namespace: default
spec:
  chart:
    spec:
      chart: bitnami-nginx/artifacts/nginx-server/helm-chart/nginx/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 0s
  valuesFrom:
  - kind: ConfigMap
    name: pctl-profile-nginx-server-defaultvalues
    valuesKey: default-values.yaml
status: {}
