apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: pctl-profile-bitnami-nginx-nginx-server
  namespace: default
spec:
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: pctl-profile-bitnami-nginx-nginx-server
    namespace: default
  interval: 5m0s
  path: bitnami-nginx/artifacts/nginx-server/helm-chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
status: {}
