apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: pctl-profile-bitnami-nginx-nginx-server
  namespace: default
spec:
  chart:
    spec:
      chart: weaveworks-nginx/artifacts/nested-profile/nginx-server/helm-chart/nginx/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 0s
status: {}
