apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: pctl-profile-weaveworks-nginx-nginx-deployment
  namespace: default
spec:
  interval: 5m0s
  path: weaveworks-nginx/artifacts/nginx-deployment/nginx/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
status: {}
